### PR TITLE
SkellyCam integration 

### PR DESCRIPTION
**Pull request by jonmatthis**
Integrated SkellyCamWidget (from the `skellycam/development` branch) into this application by replacing `CameraMenu` (left in as `old_CameraMenu`) with `SkellyCameraMenu`

Things that work: 
- The basic camera view functionality, most/all of the buttons in the skellycam interface

Things that still need done before its properly functional: 

- Need remove/hide the `record` buttons from SkellyCam
- Need make the `Save Snapshot` button work (possibly by hijacking the `new_frames` signal emitted by `SkellyCamWidget.SkellyCamManager.FrameGrabber` (note, use `FramePayload.get_image()` to get the image as a `np.ndarray`)

NOTE - 
- Also, the cameras don't shut down process when closing the GUI window - not technically a blocker from 'functional' but definitely something that needs fixing to avoid zombie cameras lol 🧟 📷 
- If you want to make changes to SkellyCam:
    - Fork the `skellycam` repo (being sure to get all the branches, not just main - we're working on the `development` branch in this case)
    - Update the github repo URL in the skellycam dependency in `pyproject.toml` to point towards your fork
    - If using `poetry` when you push a commit to the fork, delete the `poetry.lock` file and run `poetry update`
    - If using `pip`, I think `pip install . --upgrade` might work? `pip install . --force-reinstall` will definitely work but will take longer
    
 
 Whee!

### CODE REVIEW

**Comment by jonmatthis** [comment]
@philipqueen might want to take a gander at this as an opportunity to scope out 'new skellycam' in action 💀 📸 ✨

**Comment by aaroncherian** [comment]
Gotcha thanks. So just to clarify, it doesn't capture a snapshot yet right? Would you want me to take a look at making that happen?

**Comment by aaroncherian** [comment]
@jonmatthis have to do some testing but I believe I figured out how to get the snapshot capturing (and the rest of the pipeline) to work properly!

**Comment by aaroncherian** [comment]
image

Got it working on my laptop. No blender stuff, and there's still some CSS issues/things that could be formatted better. But hopefully in good shape to use at SfN

**Pull request merged**
